global:
  scrape_interval:     5s
  evaluation_interval: 5s
  
rule_files:
   - "prometheus_rules.yml"  

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    honor_labels: true
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
    - targets: ['prometheus:9090']
   
  - job_name: 'grafana'
    honor_labels: true
    static_configs:
    - targets: ['grafana:3000']
      
