global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
   - "prometheus_rules.yml"  

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
    - targets: ['localhost:9091']

  - job_name: 'node-exporter'
    honor_labels: true
    static_configs:
    - targets: ['localhost:9100']

